extensions: ['.mp4', '.avi', '.mkv']
load_folder: './movies'
target_folder: './target'
themoviedb_key: 'themoviedb_key'
themoviedb_lang: 'en'
remove_folder: true
telegram_api_key: someapikey
telegram_chat_id: somechatid
